sudo: required
dist: trusty

language: python

python:
    - "2.7"

install:
    - pip install -r ./.ci/python_requirements
    - pip install nose

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise
        packages:
            - doxygen
            - libpq-dev
            - clang-3.7
            - libc6-dev-i386
            - gcc-multilib
            - thrift-compiler

    postgresql: "9.3"

script:
    - ./change_clang_version.py
    - . test_env_setup.sh
    - nosetests tests/unit_test/
    - ./build_package.py -o $TEST_CODECHECKER_PACKAGE_DIR -v
    - export CODECHECKER_DB_DRIVER=psycopg2
    - ./test_package.py -p $TEST_CODECHECKER_DIR -v $TEST_CLANG_VERSION --postgresql --dbport $TEST_DBPORT --dbusername $TEST_DBUSERNAME
    - export CODECHECKER_DB_DRIVER=pg8000
    - ./test_package.py -p $TEST_CODECHECKER_DIR -v $TEST_CLANG_VERSION --postgresql --dbport $TEST_DBPORT --dbusername $TEST_DBUSERNAME
    - unset CODECHECKER_DB_DRIVER
    - ./test_package.py -p $TEST_CODECHECKER_DIR -v $TEST_CLANG_VERSION
    - nosetests tests/quickcheck_test/

